config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :games, only: :index do
    get '/compute_score', to: 'scores#compute_score'
    post :question_selector, on: :member
    resources :questions, only: %i[show] do
      resources :answers, only: :create
      get '/answer', to: "answers#answer"
    end
    patch 'reset', on: :member
  end

  resources :scores, only: %i[index show create]
  get '/infos', to: 'users#show', as: :infos
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :proposal
  belongs_to :user

  def question
    proposal.question
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :scores, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :proposals, through: :questions
  has_many :answers, through: :proposals
  validates_presence_of :title
  has_one_attached :photo_game

  def over?(user)
    questions = user.remaining_questions(self)
    questions.empty?
  end

  def no_question?(user)
    questions = user.remaining_questions(self)
    questions.empty? && self.questions.empty?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :question
  has_many :answers, dependent: :destroy
  validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :game
  has_many :proposals, dependent: :destroy
  has_many :answers, through: :proposals
  validates :content, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :point, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :scores, dependent: :destroy
  has_many :games, through: :scores
  has_many :answers, dependent: :destroy
  validates_presence_of :nickname
  validates :firstname, presence: true, uniqueness: { scope: :lastname }
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  has_one_attached :photo_avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def remaining_questions(game)
    game.questions.reject do |question|
      question.answers.select { |answer| answer.user == self }.any?
    end
    # answered_question_ids = answers.map { |answer| answer.question.id }
    # game.questions.where.not(id: answered_question_ids)
  end

  def total_score
    return scores.map(&:point).sum
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @user = current_user
    @proposal = Proposal.find(params[:proposal_id])
    @answer = Answer.new(user_id: @user.id, proposal_id: @proposal.id)
    @answer.save!
    if next_question.nil?
      redirect_to score_path
    else
      redirect_to question_selector_game_path
    end
  end

  def answer
    @game = Game.find(params[:game_id])
    @user = current_user
    @proposal = Proposal.find(params[:proposal_id])
    @answer = Answer.new(user_id: @user.id, proposal_id: @proposal.id)
    @answer.save!
    @question = Question.find(params[:question_id])
    @next_question = next_question
    if next_question.nil?
      redirect_to game_compute_score_path(@game)
    else
      redirect_to game_question_path(@game, @next_question)
    end
  end

  private

  def next_question
    user = current_user
    @next_question = user.remaining_questions(@game).sample
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :nickname])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[question_selector reset]
  def index
    @games = Game.all
    @demo_cards = %w[demo-card--step1 demo-card--step2 demo-card--step3 demo-card--step4 demo-card--step5]
    @card_bg_colors = %w[bg-primary bg-success bg-warning bg-info bg-danger bg-dark]
  end

  def question_selector
    redirect_to question game_question(next_question)
    # doit rediriger vers la show d'une question
  end

  def reset
    @game.questions.each do |question|
      question.answers.each { |answer| answer.destroy if answer.user }
    end
    redirect_to games_path, status: :see_other
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def next_question
    user = current_user
    @next_question = user.remaining_questions(@game).sample
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save!
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: :show
  def show
    @proposals = @question.proposals
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: :show

  def index
    @user = current_user
    @scores = Score.where(user: @user)
    @final_score = 0
    @scores.each do |score|
      @final_score += score.game.questions.count * 10
    end
    @final_score
  end

  def show; end

  def compute_score
    @user = current_user
    @score = Score.new(user: @user)
    @game = Game.find(params[:game_id])
    @score.game = @game
    point = 0
    # answer = Answer.find(params[:user_id, :proposal_id])
    @game.answers.select { |answer| answer.user == @user }.each do |answer|
      point += 1 if answer.proposal.correct == true
    end
    @score.point = 10 * point
    redirect_to score_path(@score), notice: "Score is #{@score}" if @score.save!
  end

  private

  def set_score
    @score = Score.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @level = 1
    games = @user.games
    @level = games.size + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/show.html.erb
<!-- Background video -->
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>

<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1><%= @chatroom.name %></h1>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

    <%= simple_form_for [@chatroom, @message],
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" } ,class: "d-flex-button"} do |f|
    %>
      <%= f.input :content,
        label: false,
        placeholder: "Message",
        wrapper_html: {class: "flex-grow-1"}
      %>
      <%= f.submit "Send", class: "btn btn-primary-chatroom" %>
    <% end %>
</div>

app/views/games/index.html.erb
<% content_for :for_head do %>
  <meta name="turbo-visit-control" content="reload">
<% end %>

<!-- Background video -->
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>

<!-- la gride de trajictoire -->
<section id=timeline>
	<h1>Trajectory of Your Space 🚀Ship🚀</h1>
	<div class="demo-card-wrapper" data-controller="auto-scroll">


  <% @games.each_with_index do |game, index| %>

    <div class='demo-card <%= @demo_cards[index % @demo_cards.size ] %>'>
      <div class="container">

        <% if game.no_question?(current_user) %>
          <div class='card bg-dark'>
            <% if game.photo_game.attached? %>
              <div class="imgBx ">
                <%= cl_image_tag(game.photo_game.key,
                      width: 400, height: 400, crop: :fit) %>
              </div>
            <% end %>
            <div class="contentBx ">
              <h2>Level <%= index + 1 %></h2>
              <div class="size">
                <h3>Questions:</h3>
                <% for i in(1..game.questions.count) do %>
                  <span><%= i %></span>
                <% end %>
              </div>
              <div class="color">
                <h3>Difficulty:</h3>
                <% for i in(1..index+1) do %>
                  <span></span>
                <% end %>
              </div>
              <h3>There are no question</h3>
            </div>
          </div>

        <% elsif game.over?(current_user) %>
          <div class='card bg-secondary'>
            <% if game.photo_game.attached? %>
              <div class="imgBx ">
                <%= cl_image_tag(game.photo_game.key,
                      width: 400, height: 400, crop: :fit) %>
              </div>
            <% end %>
            <div class="contentBx ">
              <h2>Level <%= index + 1 %></h2>
              <div class="size">
                <h3>Questions:</h3>
                <% for i in(1..game.questions.count) do %>
                  <span><%= i %></span>
                <% end %>
              </div>
              <div class="color">
                <h3>Difficulty:</h3>
                <% for i in(1..index+1) do %>
                  <span></span>
                <% end %>
              </div>
              <h3>Level cleared</h3>
              <% questions = current_user.remaining_questions(game) %>
              <%= link_to "Retry", reset_game_path(game.id), data:{turbo_method: :patch}, class: "btn" %>
            </div>
          </div>

        <% else %>
          <div class="card <%= @card_bg_colors[index % @card_bg_colors.size] %>" data-auto-scroll-target=button>
            <% if game.photo_game.attached? %>
              <div class="imgBx ">
                <%= cl_image_tag(game.photo_game.key,
                      width: 400, height: 400, crop: :fit) %>
              </div>
            <% end %>
            <div class="contentBx ">
              <h2>Level <%= index + 1 %></h2>
              <div class="size">
                <h3>Questions:</h3>
                <% for i in(1..game.questions.count) do %>
                  <span><%= i %></span>
                <% end %>
              </div>
              <div class="color">
                <h3>Difficulty:</h3>
                <% for i in(1..index+1) do %>
                  <span></span>
                <% end %>
              </div>
                <% questions = current_user.remaining_questions(game) %>
                <%= link_to "Start Now", game_question_path(game, questions[0]),class: "btn" %>
            </div>
          </div>
        <% end %>

      </div>
		</div>

  <% end %>

	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for? :for_head %>
      <%= yield :for_head %>
    <% end %>

    <link rel="shortcut icon" href="https://img.icons8.com/external-justicon-blue-justicon/344/external-rocket-science-justicon-blue-justicon.png" />
    <link rel="apple-touch-icon" href="https://img.icons8.com/external-justicon-blue-justicon/344/external-rocket-science-justicon-blue-justicon.png" />
    <title>Spacekids</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Learning can be fun!">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>


  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div style="font-family: 'Space Age', sans-serif;" id="message-<%= message.id %>">
  <small style="font-family: 'Space Age', sans-serif;">
    <strong style="font-size: 17px"><%= message.user.nickname %></strong>
    <i style="font-size: 17px"><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p style="font-size: 25px"><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<body id="page-top" class="index" data-pinterest-extension-installed="cr1.3.4">

<style>
@import url('http://fonts.cdnfonts.com/css/space-age');
</style>

    <!-- Header -->
    <header>
          <video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
          </video>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">HELLO SPACE KIDS</div>
                <div class="intro-heading">🚀 ☄️ Start filling the space in one click ☄️ 🚀</div>
                <%= link_to "Start", games_path, class: "page-scroll btn btn-xl"  %>
            </div>
        </div>
    </header>

app/views/questions/show.html.erb
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>



    <main class="main_home">

        <section class="card-area-score" data-controller='pop-up'>
          <!-- Card: Question -->
          <div data-pop-up-target = "screen"></div>
          <section class="card-section">
            <div class="cards">
              <div class="flip-card">
                <div class="flip-card__container">
                  <div class="card-front">
                    <div class="card-front__tp card-front__tp--city">

                      <% game = @question.game %>
                      <% questions = game.questions %>
                      <h2 class="card-front__heading">
                        Question n°<%= questions.count - current_user.remaining_questions(game).count + 1%>
                      </h2>
                      <p class="card-front__text-price">
                        Space kids
                      </p>
                    </div>

                    <div class="card-front__bt">
                      <p class="card-front__text-view card-front__text-view--city">
                        View Question
                      </p>
                    </div>
                  </div>

                  <div class="card-back">
                    <video class="video__container" autoplay muted loop>
                      <source class="video__media" src="<%= @question.image %>" type="video/mp4">
                    </video>
                  </div>
                </div>
              </div>

                    <div class="inside-page">
                        <div class="inside-page__container">
                          <div class="row">
                            <h3 class="inside-page__heading inside-page__heading--city mb-5">
                               <%= @question.content %>
                            </h3>


                              <% @proposals.shuffle.each do |p| %>
                                <%= link_to "#{p.content}", game_question_answer_path(@question.game, @question, :proposal_id => p.id), class: "inside-page__btn inside-page__btn--city", data:{correct: p.correct, controller: 'color-answers', action: 'click->pop-up#display click->color-answers#color'} %>
                              <% end  %>

                          </div>
                       </div>
                    </div>
                </div>
            </section>
        </section>
    </main>

app/views/scores/index.html.erb
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>

<h2 class ="mt-5" style="font-family: 'Space Age', sans-serif;">My scores</h2>

<div class = "container">
  <div class = "row">
    <ul class="mt-5">
      <table class = "table">
        <thead>
          <tr style="color: white">
            <th>Level</th>
            <th>Points</th>
            <th>Max Points</th>
          </tr>
        </thead>
        <tbody>
          <% @scores.each_with_index do |score, i| %>
            <tr style="color: white">
              <td>Level <%= i + 1 %></td>
              <td><%= score.point %></td>
              <td><%= score.game.questions.count * 10 %></td>
            </tr>
          <% end %>
          <tr style="color: white">
            <th>Total</th>
            <th><%= @user.total_score %></th>
            <th><%= @final_score %></th>
          </tr>
        </tbody>
      </table>
    </ul>
  </div>
</div>

app/views/scores/show.html.erb
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
<section class="random-bg">
    <h2 class="BigTitleH1" style="font-family: 'Space Age', sans-serif;">Score</h2>
    <div class="winner-wrap">
      <div class="medal-box"><i class="fas fa-medal"></i></div>
          <img src="" alt="" class="img-thumbnail">
          <div class="LEVELEND">LEVEL END</div>
      <h1><%= @score.game.title %> Space Kids</h1>
      <h2>User : <%= @score.user.firstname %></h2>
      <h2><%= @score.point %> Points</h2>
      <div class="right-ribbon"></div>
      <div class="left-ribbon"></div>
    </div>
    <div class="BackBtnList"><%= link_to "Back to the list of the games", games_path ,class: "btn btn-outline-light" %></div>
  </section>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/4825/4825026.png" %>
      <p class="LogoText">Space kids</p>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- audio -->

    <!-- finish audio-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Admin", admin_root_path, class: "nav-link" %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= link_to "Scores", scores_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <!--a href="http://localhost:3000/chatrooms/1", class="nav-link">Message</a-->
            <% if Chatroom.first.present? %>
              <%= link_to "Message", chatroom_path(Chatroom.first), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="dropdown"><%= current_user.nickname %></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "#{current_user.nickname}'s profil", infos_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<!-- New nav bar-->

app/views/users/show.html.erb
<video id="background-video" autoplay loop muted>
             <source src="https://thumbs.gfycat.com/RemoteImpishBlackbear-mobile.mp4" type="video/mp4">
</video>



<div class="center">
  <div class="card" style="margin-top: 100px;">
  <h1 class="textSpace"> << Show your user information </h1>
    <div class="additional" style="overflow: scroll; white-space:nowrap">
      <div class="user-card">
        <div class="level center">
          <h4>Level <%= @level%></h4>
        </div>
        <div class="points center">
           <%= @user.total_score %> Points
        </div>

        <svg width="110" height="110" viewBox="0 0 250 250" xmlns="https://cdn2.iconfinder.com/data/icons/people-flat-design/64/People-Man-Boy-Kid-Happy-Smile-Avatar-1024.png" role="img" aria-labelledby="title desc" class="center">
          <title id="title">Teacher</title>
          <desc id="desc">Cartoon of a Caucasian woman smiling, and wearing black glasses and a purple shirt with white collar drawn by Alvaro Montoro.</desc>
          <style>
            .skin { fill: #eab38f; }
            .eyes { fill: #1f1f1f; }
            .hair { fill: #2f1b0d; }
            .line { fill: none; stroke: #2f1b0d; stroke-width:2px; }
          </style>
          <defs>
            <clipPath id="scene">
              <circle cx="125" cy="125" r="115"/>
            </clipPath>
            <clipPath id="lips">
              <path d="M 106,132 C 113,127 125,128 125,132 125,128 137,127 144,132 141,142  134,146  125,146  116,146 109,142 106,132 Z" />
            </clipPath>
          </defs>
          <circle cx="125" cy="125" r="120" fill="rgba(0,0,0,0.15)" src="https://cdn2.iconfinder.com/data/icons/people-flat-design/64/People-Man-Boy-Kid-Happy-Smile-Avatar-1024.png" alt="">
        </svg>
        <img src="https://cdn2.iconfinder.com/data/icons/people-flat-design/64/People-Man-Boy-Kid-Happy-Smile-Avatar-1024.png" alt="" style="width: 150px; height: 150px; position: relative; top: 190px;">
      </div>
      <div class="more-info">
        <h1><%= @user.nickname %>'s Profil</h1>
        <hr style= "color:#fff;">
        <div class="coords">
          <span class="mx-3">Email :  <%= @user.email %></span>
          <span class="mx-3">Last Name :  <%= @user.lastname %></span>
          <span class="mx-3">First Name :  <%= @user.firstname %></span>
        </div>
        <hr style= "color:#fff;">

        <div class="coords">
         <h3>All wrong answers</h3>
            <table class = "table">
              <thead>
                <tr style="color: white">
                  <th>Game</th>
                  <th>Question</th>
                  <th>Proposal</th>
                  <th>Right answer</th>
                </tr>
              </thead>


              <tbody>
                <% @user.answers.each do |answer| %>
                  <tr style="color: white">
                    <% if answer.proposal.correct == false %>
                      <% game = answer.proposal.question.game %>
                      <td><%= game.title %></td>
                      <td><%= answer.proposal.question.content %></td>
                      <td><%= answer.proposal.content %></td>
                      <td><%= answer.proposal.question.proposals.find_by(correct:true).content %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>

        </div>
      </div>
    </div>